### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/misik#7]
## Довести до финала фрагменты:

- [x] Navigation
- [x] Hero
- [x] About 
- [x] Services
- [x] Work format
- [x] Feedback
- [x] Footer

## Прогресс

- [x] Форма обратной связи (функционал)
- [x] Carousel
- [x] Контакты (страница)
- [x] Navigation фикс
- [x] Accordeon
- [x] SEO
- [x] Drawer
- [x] Favicon
- [x] Ссылки в футере
- [x] Privacy policy
- [x] Карта scrollable, мешает скроллить
- [x] В картинке в about экспортирован не тот слой
- [x] У аккордеона есть кривой сдвиг
- [x] Поменять основную сетку
- [x] На странице контактов нет карты
- [x] url uglify
- [x] В форме проходит сценарий когда все поля пустые
- [x] Текста не отформатированы  (абзацы)
- [x] ?Анкоры без анимации?
- [ ] У карусели кривой space-between
- [x] Убрать таймер у второй карусели
- [x] Кнопка копирования
- [x] CD
- [x] Загрузить шрифты
- [x] Карта
- [x] SpyScroll
- [x] Перевод системных сообщений (отправить, заказать доставку и тп)
- [x] drawer не работает на странице контактов (и лагает)
- [x] криво работает spyScroll
- [x] нету страницы privacy-policy
- [x] ненужные якоря на странице контактов
- [x] криво сверстана типография на странице контактов
- [x] маркеры на карте
